In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import moment

df = pd.read_csv(r"C:\Users\Julian Quijano\Desktop\Data-FA4.csv")

normal_df = np.array(df['Normal'])  # Female height
sr_df = np.array(df['SK_right'])  # Female age at marriage
sl_df = np.array(df['SK_left'])  # Obituary data (age of death for females)
uniform_df = np.array(df['Uniform'])  # Amount of cola put into a 12oz container by a machine

# 1 Find the (a) first, (b) second, (c) third, and (d ) fourth moments for each of the sets of data
# (normal, skewed-right, skewed-left, uniform).

# 1st Moment
normal_m1, sr_m1, sl_m1, uniform_m1 = (
	str(np.mean(normal_df)),
	str(np.mean(sr_df)),
	str(np.mean(sl_df)),
	str(np.mean(uniform_df))
)

# 2nd Moment
normal_m2, sr_m2, sl_m2, uniform_m2 = (
	str(np.mean(normal_df**2)),
	str(np.mean(sr_df**2)),
	str(np.mean(sl_df**2)),
	str(np.mean(uniform_df**2))
)

# 3rd Moment
normal_m3, sr_m3, sl_m3, uniform_m3 = (
	str(np.mean(normal_df**3)),
	str(np.mean(sr_df**3)),
	str(np.mean(sl_df**3)),
	str(np.mean(uniform_df**3))
)

# 4th Moment
normal_m4, sr_m4, sl_m4, uniform_m4 = (
	str(np.mean(normal_df**4)),
	str(np.mean(sr_df**4)),
	str(np.mean(sl_df**4)),
	str(np.mean(uniform_df**4))
)

# 2 Find the (a) first, (b) second, (c) third, and (d) fourth moments about the mean for each of the sets of data
# (normal, skewed-right, skewed-left, uniform).

# 1st Moment about the Mean
normal_cm1, sr_cm1, sl_cm1, uniform_cm1 = (
	str(moment(normal_df)),
	str(moment(sr_df)),
	str(moment(sl_df)),
	str(moment(uniform_df))
)

# 2nd Moment about the Mean
normal_cm2, sr_cm2, sl_cm2, uniform_cm2 = (
	str(moment(normal_df, moment=2)),
	str(moment(sr_df, moment=2)),
	str(moment(sl_df, moment=2)),
	str(moment(uniform_df, moment=2))
)

# 3rd Moment about the Mean
normal_cm3, sr_cm3, sl_cm3, uniform_cm3 = (
	str(moment(normal_df, moment=3)),
	str(moment(sr_df, moment=3)),
	str(moment(sl_df, moment=3)),
	str(moment(uniform_df, moment=3))
)

# 4th Moment about the Mean
normal_cm4, sr_cm4, sl_cm4, uniform_cm4 = (
	str(moment(normal_df, moment=4)),
	str(moment(sr_df, moment=4)),
	str(moment(sl_df, moment=4)),
	str(moment(uniform_df, moment=4))
)

# Find the (a) first, (b) second, (c) third, and (d) fourth moments about the number 75 for the set of female height
# measurements.

c = 75  # moments about 75
m1_75 = str(np.mean(normal_df - c))
m2_75 = str(np.mean((normal_df - c)**2))
m3_75 = str(np.mean((normal_df - c)**3))
m4_75 = str(np.mean((normal_df - c)**4))

# Raw
print('\nMoment 1 for all tables:')
print('Female Height: ' + normal_m1)
print('Female Age at Marriage: ' + sr_m1)
print('Obituary data (age of death for females): ' + sl_m1)
print('Amount of cola put into a 12oz container by a machine: ' + uniform_m1)

print('\nMoment 2 for all tables: ')
print('Female Height: ' + normal_m2)
print('Female Age at Marriage: ' + sr_m2)
print('Obituary data (age of death for females): ' + sl_m2)
print('Amount of cola put into a 12oz container by a machine: ' + uniform_m2)

print('\nMoment 3 for all tables: ')
print('Female Height: ' + normal_m3)
print('Female Age at Marriage: ' + sr_m3)
print('Obituary data (age of death for females): ' + sl_m3)
print('Amount of cola put into a 12oz container by a machine: ' + uniform_m3)

print('\nMoment 4 for all tables: ')
print('Female Height: ' + normal_m4)
print('Female Age at Marriage: ' + sr_m4)
print('Obituary data (age of death for females): ' + sl_m4)
print('Amount of cola put into a 12oz container by a machine: ' + uniform_m4)

# Around the Mean
print('\nMoment 1 around the mean for all tables: ')
print('Female Height: ' + normal_cm1)
print('Female Age at Marriage: ' + sr_cm1)
print('Obituary data (age of death for females): ' + sl_cm1)
print('Amount of cola put into a 12oz container by a machine: ' + uniform_cm1)

print('\nMoment 2 around the mean for all tables: ')
print('Female Height: ' + normal_cm2)
print('Female Age at Marriage: ' + sr_cm2)
print('Obituary data (age of death for females): ' + sl_cm2)
print('Amount of cola put into a 12oz container by a machine: ' + uniform_cm2)

print('\nMoment 3 around the mean for all tables: ')
print('Female Height: ' + normal_cm3)
print('Female Age at Marriage: ' + sr_cm3)
print('Obituary data (age of death for females): ' + sl_cm3)
print('Amount of cola put into a 12oz container by a machine: ' + uniform_cm3)

print('\nMoment 4 around the mean for all tables: ')
print('Female Height: ' + normal_cm4)
print('Female Age at Marriage: ' + sr_cm4)
print('Obituary data (age of death for females): ' + sl_cm4)
print('Amount of cola put into a 12oz container by a machine: ' + uniform_cm4)

# Moment around 75 for Female Height
print('\nMoments around 75 for Female Height: ')
print('Moment 1: ' + m1_75)
print('Moment 2: ' + m2_75)
print('Moment 3: ' + m3_75)
print('Moment 4: ' + m4_75)

# Using the results of items 2 and 3 for the set of female height measurements, verify the relations between the moments
m2 = float(normal_m2) - float(normal_m1)**2
m3 = float(normal_m3) - 3 * float(normal_m1) * float(normal_m2) + 2 * float(normal_m1)**3
m4 = (float(normal_m4) - 4 * float(normal_m1) * float(normal_m3) + 6 * (float(normal_m1)**2) * float(normal_m2) - 3 *
	(float(normal_m1)**4))

# Verifying
normal_cm2 = float(normal_cm2)
normal_cm3 = float(normal_cm3)
normal_cm4 = float(normal_cm4)
print('\nVerifying:')
print('m2: ' + str(round(m2, 3)) + ' = ' + ('normal_cm2: ') + str(round(normal_cm2, 3)))
print('m3: ' + str(round(m3, 3)) + ' = ' + ('normal_cm3: ') + str(round(normal_cm3, 3)))
print('m4: ' + str(round(m4, 3)) + ' = ' + ('normal_cm4: ') + str(round(normal_cm4, 3)))

Moment 1 for all tables:
Female Height: 65.12
Female Age at Marriage: 35.48
Obituary data (age of death for females): 74.2
Amount of cola put into a 12oz container by a machine: 12.056000000000001

Moment 2 for all tables:
Female Height: 4248.92
Female Age at Marriage: 1437.72
Obituary data (age of death for females): 5925.4
Amount of cola put into a 12oz container by a machine: 145.426

Moment 3 for all tables:
Female Height: 277770.92
Female Age at Marriage: 68292.44
Obituary data (age of death for females): 489458.8
Amount of cola put into a 12oz container by a machine: 1755.15776

Moment 4 for all tables:
Female Height: 18194173.64
Female Age at Marriage: 3797594.04
Obituary data (age of death for females): 41396161.48
Amount of cola put into a 12oz container by a machine: 21194.5933

Moment 1 around the mean for all tables:
Female Height: 0.0
Female Age at Marriage: 0.0
Obituary data (age of death for females): 0.0
Amount of cola put into a 12oz container by a machine: 0.0

Moment 2 around the mean for all tables:
Female Height: 8.3056
Female Age at Marriage: 178.8896
Obituary data (age of death for females): 419.76000000000005
Amount of cola put into a 12oz container by a machine: 0.07886400000000006

Moment 3 around the mean for all tables:
Female Height: -0.47174400000011407
Female Age at Marriage: 4588.1283840000015
Obituary data (age of death for females): -12498.264000000003
Amount of cola put into a 12oz container by a machine: 0.00033523199999977105

Moment 4 around the mean for all tables:
Female Height: 160.94862592000004
Female Age at Marriage: 210642.88343552008
Obituary data (age of death for females): 927289.7472
Amount of cola put into a 12oz container by a machine: 0.011251168512000026

Moments around 75 for Female Height:
Moment 1: -9.88
Moment 2: 105.92
Moment 3: -1211.08
Moment 4: 14572.64

Verifying:
m2: 8.306 = normal_cm2: 8.306
m3: -0.472 = normal_cm3: -0.472
m4: 160.949 = normal_cm4: 160.949